set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'altercation/vim-colors-solarized'
Plugin 'PotatoesMaster/i3-vim-syntax'
Plugin 'evanmiller/nginx-vim-syntax'

call vundle#end()
filetype plugin indent on

syntax enable

set background=dark
set cursorline
set encoding=utf-8
set expandtab
set number
set incsearch
set hlsearch
set lazyredraw
set mouse=a
set nobackup
set number
set shiftwidth=2
set t_Co=256
set tabstop=2

let g:solarized_termcolors=256

colorscheme solarized

nmap <silent> <F11> :let @/=''<CR>
nmap <silent> <F12> :NERDTreeToggle<CR>

autocmd Syntax c,cpp,vim setlocal foldmethod=syntax
autocmd Syntax c,cpp,vim normal zR


" lazyredraw is a workaround for https://github.com/vim/vim/issues/282
