#

fpath=( /home/black/src/library/zsh/completion /home/black/src/library/zsh/prompt ${fpath[@]} )
path=( /opt/firefox $path )

# Set up the prompt

autoload -Uz promptinit
promptinit
prompt black 8bit cyan green blue white

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

bindkey '^[[Z' reverse-menu-complete

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
#zstyle ':completion:*' menu select=long
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'


# Aliases
# ---
alias ls='ls --color'
alias l='ls -lFh'
alias la='ls -laFh'
alias lt='ls -lFtr'

alias grep='grep --color'

alias -g L='| less'

alias T='TERM=xterm-color '

alias anspub='ansible-playbook dns.yml -i inventory/atono -l ns-public -s -K -t file'
alias anspri='ansible-playbook dns.yml -i inventory/atono -l ns-private -s -K -t file'
alias gmom='git merge origin/master'
